// useCases.js

export const useCases = [
  // Content/Media
  { id: 1, domain: "Content/Media", title: "Text Summarization", problem: "How can we quickly understand long documents or articles?", solution: "AI summarizes lengthy content into concise, easy-to-read summaries, saving time and improving productivity.", aiTool: "OpenAI GPT-4", icon: "assets/gpt4.jpg" },
  { id: 2, domain: "Content/Media", title: "Content Generation", problem: "How can businesses generate high-quality content at scale?", solution: "AI generates articles, blog posts, and marketing copy based on prompts and context.", aiTool: "GPT-4", icon: "assets/gpt4.jpg" },
  { id: 3, domain: "Content/Media", title: "Video Captioning", problem: "How can we make videos accessible to a wider audience?", solution: "AI automatically generates captions and subtitles for videos.", aiTool: "Rev AI", icon: "assets/gpt4.jpg" },
  { id: 4, domain: "Content/Media", title: "Plagiarism Detection", problem: "How can publishers ensure content originality?", solution: "AI scans and compares content to detect plagiarism and ensure authenticity.", aiTool: "Copyscape AI", icon: "assets/copyscape.png" },
  { id: 5, domain: "Content/Media", title: "Content Personalization", problem: "How can platforms tailor content to individual users?", solution: "AI recommends articles, videos, and music based on user preferences.", aiTool: "Taboola AI", icon: "assets/gpt4.jpg" },
  { id: 6, domain: "Content/Media", title: "AI-Powered Content Moderation", problem: "How can platforms automatically detect and filter inappropriate content?", solution: "AI scans and flags offensive or policy-violating content in real time, ensuring community safety.", aiTool: "Perspective API", icon: "assets/PerspectiveAPI.png" },

  // Image Processing
  { id: 7, domain: "Image Processing", title: "Image Classification", problem: "How can we automatically categorize and tag large volumes of images?", solution: "GenAI models classify images into categories, enabling fast search, organization, and content moderation.", aiTool: "Google Vision AI", icon: "assets/GoogleVisionAI.jpg" },
  { id: 8, domain: "Image Processing", title: "Object Detection", problem: "How can we identify objects in photos for security or retail?", solution: "AI detects and labels objects in images for inventory, surveillance, and more.", aiTool: "YOLOv5", icon: "assets/gpt4.jpg" },
  { id: 9, domain: "Image Processing", title: "Facial Recognition", problem: "How can we verify identities or unlock devices securely?", solution: "AI matches faces in images to user profiles for authentication and security.", aiTool: "Microsoft Face API", icon: "assets/AzureFaceAPI.jpg" },
  { id: 10, domain: "Image Processing", title: "Image-to-Text Conversion", problem: "How can we extract text from images for digital archiving?", solution: "AI uses OCR to convert images of documents into searchable, editable text.", aiTool: "Tesseract OCR", icon: "assets/TesseractAi.jpg" },
  { id: 11, domain: "Image Processing", title: "Medical Image Analysis", problem: "How can radiologists detect diseases in X-rays and MRIs?", solution: "AI highlights anomalies in medical images to assist diagnosis.", aiTool: "Aidoc AI", icon: "assets/AidocAI.jpg" },
  { id: 12, domain: "Image Processing", title: "Image Generation", problem: "How can we generate realistic images from text prompts?", solution: "AI generates images from text descriptions, enabling creative applications.", aiTool: "DALL-E", icon: "assets/DALL-E.jpg" },

  // Software Development
  { id: 13, domain: "Software Development", title: "Code Generation", problem: "How can developers speed up coding and reduce repetitive tasks?", solution: "AI generates code snippets from natural language prompts, accelerating development and reducing errors.", aiTool: "GitHub Copilot", icon: "assets/githubmark.png" },
  { id: 14, domain: "Software Development", title: "API Development", problem: "How can we quickly create backend APIs for applications?", solution: "AI generates boilerplate code for RESTful APIs, saving development time.", aiTool: "OpenAI Codex", icon: "assets/gpt4.jpg" },
  { id: 15, domain: "Software Development", title: "Testing Automation", problem: "How can we automate software testing to catch bugs early?", solution: "AI generates test scripts and test data, improving code quality and reducing manual testing.", aiTool: "Selenium AI", icon: "assets/gpt4.jpg" },
  { id: 16, domain: "Software Development", title: "Documentation Generation", problem: "How can we generate technical documentation automatically?", solution: "AI generates API documentation, user manuals, and code comments from source code.", aiTool: "Doxygen AI", icon: "assets/gpt4.jpg" },
  { id: 17, domain: "Software Development", title: "Code Review", problem: "How can we improve code quality and catch potential issues?", solution: "AI analyzes code for bugs, security vulnerabilities, and performance issues.", aiTool: "SonarQube AI", icon: "assets/gpt4.jpg" },
  { id: 18, domain: "Software Development", title: "Bug Prediction", problem: "How can teams predict bugs before deployment?", solution: "AI analyzes code changes and historical data to predict potential bugs and suggest fixes.", aiTool: "DeepCode AI", icon: "assets/DeepCodeAi.png" },

  // Customer Experience
  { id: 19, domain: "Customer Experience", title: "Sentiment Analysis", problem: "How can businesses gauge customer sentiment from reviews and social media?", solution: "AI analyzes text to detect sentiment, helping companies understand customer feedback and improve services.", aiTool: "IBM Watson NLU", icon: "assets/IBMWastson.png" },
  { id: 20, domain: "Customer Experience", title: "Recommendation System", problem: "How can platforms personalize content for users?", solution: "AI recommends products, articles, or media based on user preferences and behavior, boosting engagement.", aiTool: "Amazon Personalize", icon: "assets/AmazonPersonalizelogo.jpg" },
  { id: 21, domain: "Customer Experience", title: "Emotion Detection in Calls", problem: "How can businesses understand customer emotions during support calls?", solution: "AI analyzes voice tone and language to detect emotions, helping agents respond empathetically.", aiTool: "Cogito AI", icon: "assets/gpt4.jpg" },
  { id: 22, domain: "Customer Experience", title: "Chatbots", problem: "How can we create intelligent chatbots for customer support?", solution: "AI powers chatbots to understand natural language queries and provide instant responses.", aiTool: "Google Dialogflow", icon: "assets/gpt4.jpg" },
  { id: 23, domain: "Customer Experience", title: "Voice Assistants", problem: "How can we create voice-enabled applications for users?", solution: "AI-powered voice assistants understand commands and automate home tasks.", aiTool: "Amazon Alexa", icon: "assets/AmazonAlexa.jpg" },
  { id: 24, domain: "Customer Experience", title: "Personalization", problem: "How can platforms personalize content for users?", solution: "AI recommends products, articles, or media based on user preferences and behavior, boosting engagement.", aiTool: "Amazon Personalize", icon: "assets/AmazonPersonalizelogo.jpg" },

  // ... rest of the code remains the same ...
  { id: 25, domain: "Knowledge Management", title: "Document Q&A", problem: "How can users quickly find answers in large documents?", solution: "GenAI answers questions by extracting relevant information from documents, improving knowledge discovery.", aiTool: "OpenAI GPT-4", icon: "/assets/gpt4.jpg" },
  { id: 26, domain: "Knowledge Management", title: "Knowledge Graph", problem: "How can we build a knowledge graph for better search and understanding?", solution: "AI creates a semantic network of entities and their relationships, enabling more sophisticated search.", aiTool: "Google Knowledge Graph", icon: "/assets/GoogleVisionAI.jpg" },
  { id: 27, domain: "Knowledge Management", title: "Document Summarization", problem: "How can we quickly understand long documents or articles?", solution: "AI summarizes lengthy content into concise, easy-to-read summaries, saving time and improving productivity.", aiTool: "OpenAI GPT-4", icon: "/assets/gpt4.jpg" },
  { id: 28, domain: "Knowledge Management", title: "Document Translation", problem: "How can we translate documents efficiently?", solution: "AI translates text from one language to another, enabling global communication.", aiTool: "Google Translate AI", icon: "/assets/GoogleVisionAI.jpg" },
  { id: 29, domain: "Knowledge Management", title: "Document Classification", problem: "How can we automatically categorize and tag large volumes of documents?", solution: "GenAI models classify documents into categories, enabling fast search, organization, and content moderation.", aiTool: "Google Vision AI", icon: "/assets/GoogleVisionAI.jpg" },
  { id: 30, domain: "Knowledge Management", title: "Automated Knowledge Base Updates", problem: "How can organizations keep their knowledge bases up to date?", solution: "AI monitors new documents and updates the knowledge base automatically with relevant information.", aiTool: "Guru AI", icon: "/assets/gpt4.jpg" },

  // Accessibility
  { id: 31, domain: "Accessibility", title: "Speech-to-Text", problem: "How can we transcribe meetings, calls, or audio content efficiently?", solution: "AI converts speech to text in real time, enabling searchable transcripts and accessibility features.", aiTool: "AWS Transcribe", icon: "awsTranscribe.png" },
  { id: 32, domain: "Accessibility", title: "Text-to-Speech", problem: "How can we convert text to speech for accessibility?", solution: "AI converts written text into natural-sounding speech, making content accessible to users with hearing impairments.", aiTool: "Amazon Polly", icon: "amazonpolly.jpg" },
  { id: 33, domain: "Accessibility", title: "Screen Readers", problem: "How can we make digital content accessible to users with visual impairments?", solution: "AI-powered screen readers interpret and read aloud digital content, enabling independent browsing.", aiTool: "Apple VoiceOver", icon: "../assets/applevoiceover.jpg" },
  { id: 34, domain: "Accessibility", title: "Color Contrast", problem: "How can we ensure text and images have sufficient contrast for readability?", solution: "AI analyzes images and text to adjust contrast and color, improving readability for users with visual impairments.", aiTool: "OpenCV AI", icon: "../assets/opencv.jpg" },
  { id: 35, domain: "Accessibility", title: "Screen Magnifiers", problem: "How can we magnify digital content for users with visual impairments?", solution: "AI-powered magnifiers enlarge digital content, enabling users to see details more clearly.", aiTool: "Magnifier AI", icon: "../assets/magnifierai.jpg" },
  { id: 36, domain: "Accessibility", title: "Real-Time Sign Language Translation", problem: "How can digital platforms be more accessible to sign language users?", solution: "AI translates sign language gestures into spoken or written language in real time.", aiTool: "SignAll AI", icon: "/assets/gpt4.jpg" },

  // Finance/Security
  { id: 37, domain: "Finance/Security", title: "Fraud Detection", problem: "How can financial institutions detect fraudulent transactions in real time?", solution: "AI analyzes transaction patterns to flag suspicious activity, reducing fraud and financial losses.", aiTool: "AWS Fraud Detector", icon: "awsFraudDetector.jpg" },
  { id: 38, domain: "Finance/Security", title: "Anomaly Detection", problem: "How can organizations detect unusual activity in their systems?", solution: "AI monitors logs and network traffic to flag anomalies and potential threats.", aiTool: "Splunk AI", icon: "/assets/gpt4.jpg" },
  { id: 39, domain: "Finance/Security", title: "Credit Scoring", problem: "How can lenders assess credit risk more accurately?", solution: "AI analyzes financial history and behavior to provide fair, data-driven credit scores.", aiTool: "FICO Score AI", icon: "/assets/gpt4.jpg" },
  { id: 40, domain: "Finance/Security", title: "Risk Assessment", problem: "How can financial institutions assess the risk of investments?", solution: "AI analyzes market data, economic indicators, and historical trends to predict risk and return.", aiTool: "Quantitative AI", icon: "/assets/QuantitativeAI.jpg" },
  { id: 41, domain: "Finance/Security", title: "Cybersecurity", problem: "How can organizations protect their digital assets?", solution: "AI monitors network traffic, identifies anomalies, and provides real-time alerts for security threats.", aiTool: "Splunk AI", icon: "/assets/gpt4.jpg" },
  { id: 42, domain: "Finance/Security", title: "Automated Regulatory Compliance", problem: "How can financial institutions ensure compliance with changing regulations?", solution: "AI monitors regulatory updates and checks transactions for compliance automatically.", aiTool: "ComplyAdvantage AI", icon: "/assets/gpt4.jpg" },

  // Healthcare
  { id: 43, domain: "Healthcare", title: "Disease Diagnosis", problem: "How can doctors quickly and accurately diagnose diseases from medical images?", solution: "AI analyzes X-rays, MRIs, and CT scans to assist in early and accurate diagnosis.", aiTool: "Google Health AI", icon: "GoogleHealthAI.jpg" },
  { id: 44, domain: "Healthcare", title: "Medical Image Analysis", problem: "How can radiologists detect diseases in X-rays and MRIs?", solution: "AI highlights anomalies in medical images to assist diagnosis.", aiTool: "Aidoc AI", icon: "AidocAI.jpg" },
  { id: 45, domain: "Healthcare", title: "Personalized Medicine", problem: "How can treatments be tailored to individual patients?", solution: "AI analyzes genetic and health data to recommend personalized therapies.", aiTool: "Deep Genomics", icon: "DeepGenomics.png" },
  { id: 46, domain: "Healthcare", title: "Remote Patient Monitoring", problem: "How can healthcare providers monitor patients outside the clinic?", solution: "AI analyzes data from wearable devices to track patient health and alert providers to issues.", aiTool: "Philips HealthSuite AI", icon: "PhilipsHealthSuiteAI.png" },
  { id: 47, domain: "Healthcare", title: "Drug Discovery", problem: "How can researchers accelerate drug discovery and development?", solution: "AI analyzes vast amounts of scientific data to identify potential drug candidates.", aiTool: "DeepMind AlphaFold", icon: "DeepMindAlphaFold.png" },
  { id: 48, domain: "Healthcare", title: "Healthcare Chatbots", problem: "How can we create intelligent chatbots for healthcare?", solution: "AI powers chatbots to understand medical queries and provide instant responses.", aiTool: "Google Dialogflow", icon: "Dialogflow.png" },

  // Retail
  { id: 49, domain: "Retail", title: "Inventory Management", problem: "How can retailers optimize their inventory levels?", solution: "AI predicts demand, identifies optimal stock levels, and manages inventory across multiple channels.", aiTool: "Amazon SageMaker", icon: "AmazonSageMaker.jpg" },
  { id: 50, domain: "Retail", title: "Price Optimization", problem: "How can retailers set prices to maximize profits?", solution: "AI analyzes market data, competitor pricing, and sales history to optimize prices for optimal revenue.", aiTool: "Google Cloud Price AI", icon: "gpt4.jpg" },
  { id: 51, domain: "Retail", title: "Customer Segmentation", problem: "How can retailers better understand their customer base?", solution: "AI clusters customers based on their purchase history, browsing behavior, and demographic data.", aiTool: "Amazon Personalize", icon: "AmazonPersonalizelogo.jpg" },
  { id: 52, domain: "Retail", title: "Product Recommendations", problem: "How can retailers personalize product recommendations?", solution: "AI analyzes user behavior and preferences to suggest relevant products, increasing conversion rates.", aiTool: "Taboola AI", icon: "gpt4.jpg" },
  { id: 53, domain: "Retail", title: "Fraud Detection", problem: "How can retailers detect fraudulent transactions?", solution: "AI analyzes transaction patterns, user behavior, and device data to identify suspicious activity.", aiTool: "AWS Fraud Detector", icon: "awsFraudDetector.jpg" },
  { id: 54, domain: "Retail", title: "AI-Driven Visual Merchandising", problem: "How can retailers optimize in-store product placement?", solution: "AI analyzes shopper behavior and store layouts to suggest optimal product arrangements.", aiTool: "Vue.ai", icon: "SyteVisualAI.png" },

  // Manufacturing
  { id: 55, domain: "Manufacturing", title: "Quality Control", problem: "How can manufacturers ensure product quality?", solution: "AI analyzes production data, identifies defects, and predicts failures to prevent costly rework.", aiTool: "AWS Rekognition", icon: "AmazonRekognition.png" },
  { id: 56, domain: "Manufacturing", title: "Predictive Maintenance", problem: "How can manufacturers prevent equipment failures?", solution: "AI analyzes sensor data to predict when maintenance is needed, reducing downtime.", aiTool: "AutoGrid Flex AI", icon: "AutoGridFlexAI.jpg" },
  { id: 57, domain: "Manufacturing", title: "Supply Chain Optimization", problem: "How can manufacturers optimize their supply chain?", solution: "AI analyzes supply chain data to identify bottlenecks and suggest improvements.", aiTool: "Llamasoft AI", icon: "LlamasoftAI.png" },
  { id: 58, domain: "Manufacturing", title: "AI-Powered Robotics", problem: "How can manufacturers automate production processes?", solution: "AI controls robots to perform complex tasks with precision and efficiency.", aiTool: "DJI Terra AI", icon: "djiterra.png" },
  { id: 59, domain: "Manufacturing", title: "Production Line Optimization", problem: "How can manufacturers optimize production efficiency?", solution: "AI analyzes production data to identify bottlenecks and suggest improvements.", aiTool: "Matterport AI", icon: "MatterportAI.png" },
  { id: 60, domain: "Manufacturing", title: "AI-Powered Quality Inspection", problem: "How can manufacturers improve quality control?", solution: "AI analyzes product images to detect defects and ensure quality standards.", aiTool: "Locus Robotics AI", icon: "LocusRoboticsAI.png" },

  // Legal
  { id: 61, domain: "Legal", title: "Contract Analysis", problem: "How can lawyers quickly analyze and understand complex contracts?", solution: "AI extracts key information, identifies clauses, and highlights potential issues from legal documents.", aiTool: "OpenAI GPT-4", icon: "gpt4.jpg" },
  { id: 62, domain: "Legal", title: "Document Review", problem: "How can lawyers review large volumes of documents efficiently?", solution: "AI analyzes text, identifies relevant sections, and provides summaries for quick understanding.", aiTool: "Doxygen AI", icon: "gpt4.jpg" },
  { id: 63, domain: "Legal", title: "Legal Summarization", problem: "How can lawyers generate concise summaries of legal documents?", solution: "AI summarizes lengthy legal documents into key points and actionable insights.", aiTool: "OpenAI GPT-4", icon: "gpt4.jpg" },
  { id: 64, domain: "Legal", title: "Contract Generation", problem: "How can lawyers generate standard legal contracts?", solution: "AI generates boilerplate code for legal contracts, reducing manual effort and errors.", aiTool: "OpenAI Codex", icon: "openAiCodex.png" },
  { id: 65, domain: "Legal", title: "AI-Powered E-Discovery", problem: "How can legal teams quickly find relevant documents in litigation?", solution: "AI scans and categorizes large volumes of legal documents to identify those relevant to a case.", aiTool: "Relativity AI", icon: "RelativityAI.png" },

  // Education
  { id: 67, domain: "Education", title: "Content Generation", problem: "How can educators create engaging lesson plans and materials?", solution: "AI generates educational content, quizzes, and study materials based on curriculum standards.", aiTool: "Jasper AI", icon: "jasperAi.jpg" },
  { id: 68, domain: "Education", title: "Language Learning", problem: "How can language learning platforms personalize content?", solution: "AI recommends language exercises, vocabulary, and pronunciation based on user proficiency.", aiTool: "Amazon Personalize", icon: "../assets/AmazonPersonalizelogo.jpg" },
  { id: 69, domain: "Education", title: "Student Assessment", problem: "How can educators assess student understanding?", solution: "AI generates test questions and answers, providing instant feedback and personalized learning.", aiTool: "OpenAI GPT-4", icon: "../assets/OpenAIGPT4.jpg" },
  { id: 70, domain: "Education", title: "Curriculum Planning", problem: "How can educators plan their teaching schedules?", solution: "AI generates lesson plans, schedules, and assignments based on curriculum requirements.", aiTool: "GitHub Copilot", icon: "../assets/GitHubCopilot.jpg" },
  { id: 71, domain: "Education", title: "Personalized Learning", problem: "How can platforms personalize learning for students?", solution: "AI analyzes student performance, preferences, and learning styles to recommend tailored content.", aiTool: "Amazon Personalize", icon: "../assets/AmazonPersonalizelogo.jpg" },
  { id: 72, domain: "Education", title: "Automated Grading", problem: "How can educators grade assignments more efficiently?", solution: "AI evaluates and grades student assignments, providing instant feedback and analytics.", aiTool: "Gradescope AI", icon: "../assets/GradescopeAI.jpg" },

  // Travel
  { id: 73, domain: "Travel", title: "Flight Optimization", problem: "How can travelers find the best flight deals?", solution: "AI analyzes flight prices, schedules, and user preferences to suggest optimal travel options.", aiTool: "Google Flights AI", icon: "../assets/GoogleFlightsAI.jpg" },
  { id: 74, domain: "Travel", title: "Hotel Booking", problem: "How can travelers book hotels efficiently?", solution: "AI generates hotel recommendations, analyzes reviews, and provides booking options based on preferences.", aiTool: "Amazon Personalize", icon: "../assets/AmazonPersonalizelogo.jpg" },
  { id: 75, domain: "Travel", title: "Trip Planning", problem: "How can travelers plan their trips more efficiently?", solution: "AI suggests itineraries, activities, and transportation options based on user preferences.", aiTool: "Google Maps AI", icon: "../assets/GoogleMapsAI.jpg" },
  { id: 76, domain: "Travel", title: "Language Translation", problem: "How can travelers communicate in foreign languages?", solution: "AI translates text and speech in real time, breaking down language barriers for travelers.", aiTool: "Amazon Translate", icon: "../assets/AmazonTranslate.jpg" },
  { id: 77, domain: "Travel", title: "Travel Recommendations", problem: "How can travelers find the best places to visit?", solution: "AI analyzes user preferences, reviews, and trends to suggest personalized travel destinations.", aiTool: "Google Places AI", icon: "../assets/GooglePlacesAI.jpg" },
  { id: 78, domain: "Travel", title: "Trip Budgeting", problem: "How can travelers plan their travel expenses?", solution: "AI helps create and track travel budgets, suggesting cost-effective options and alternatives.", aiTool: "Google Sheets AI", icon: "../assets/GoogleSheetsAI.jpg" },

  // Energy
  { id: 79, domain: "Energy", title: "Energy Consumption Prediction", problem: "How can energy companies predict energy demand?", solution: "AI analyzes historical data, weather patterns, and economic indicators to forecast energy usage.", aiTool: "Google Cloud AI", icon: "../assets/GoogleCloudAI.jpg" },
  { id: 80, domain: "Energy", title: "Renewable Energy Optimization", problem: "How can renewable energy sources be optimized?", solution: "AI analyzes weather patterns, energy production, and demand to optimize renewable energy usage.", aiTool: "Google AI", icon: "../assets/GoogleAI.jpg" },
  { id: 81, domain: "Energy", title: "Smart Grid Management", problem: "How can energy grids be managed more efficiently?", solution: "AI monitors grid performance, predicts maintenance needs, and optimizes energy distribution.", aiTool: "AWS AI", icon: "../assets/AwsLogo.jpg" },
  { id: 82, domain: "Energy", title: "Energy Trading", problem: "How can energy trading be optimized?", solution: "AI analyzes market trends, weather patterns, and energy production to optimize trading decisions.", aiTool: "Google AI", icon: "../assets/GoogleAI.jpg" },

  // Agriculture
  { id: 88, domain: "Agriculture", title: "Crop Yield Prediction", problem: "How can farmers predict crop yields?", solution: "AI analyzes weather data, soil conditions, and historical yields to forecast crop production.", aiTool: "Google Cloud AI", icon: "../assets/GoogleCloudAI.jpg" },
  { id: 89, domain: "Agriculture", title: "Smart Irrigation", problem: "How can farmers optimize water usage?", solution: "AI analyzes soil moisture, weather patterns, and crop needs to optimize irrigation schedules.", aiTool: "Google Cloud AI", icon: "../assets/GoogleCloudAI.jpg" },
  { id: 90, domain: "Agriculture", title: "Pest Detection", problem: "How can farmers detect pests early?", solution: "AI analyzes plant images to identify pest infestations and suggest treatment options.", aiTool: "Google Cloud AI", icon: "../assets/GoogleCloudAI.jpg" },
  { id: 91, domain: "Agriculture", title: "AI-Powered Farm Management", problem: "How can farmers manage their farms more efficiently?", solution: "AI generates code for farm management tools, enabling real-time monitoring and data-driven decisions.", aiTool: "GitHub Copilot", icon: "../assets/GitHubCopilot.jpg" },
  { id: 92, domain: "Agriculture", title: "Soil Analysis", problem: "How can farmers analyze soil quality?", solution: "AI analyzes soil samples to identify nutrient levels and suggest optimal fertilization strategies.", aiTool: "Google Cloud AI", icon: "../assets/GoogleCloudAI.jpg" },
  { id: 93, domain: "Agriculture", title: "Automated Drone Monitoring", problem: "How can farmers monitor large fields efficiently?", solution: "AI-powered drones capture and analyze field data for crop health and yield prediction.", aiTool: "DJI Terra AI", icon: "../assets/DJITerraAI.jpg" },

  // Logistics
  { id: 94, domain: "Logistics", title: "Route Optimization", problem: "How can logistics companies optimize their delivery routes?", solution: "AI analyzes traffic patterns, weather conditions, and customer locations to suggest optimal delivery routes.", aiTool: "Google Maps AI", icon: "../assets/GoogleMapsAI.jpg" },
  { id: 95, domain: "Logistics", title: "Inventory Management", problem: "How can warehouses manage their inventory efficiently?", solution: "AI analyzes stock levels, sales data, and supplier data to optimize inventory management.", aiTool: "Amazon SageMaker", icon: "../assets/AmazonSageMaker.jpg" },
  { id: 96, domain: "Logistics", title: "Supply Chain Visibility", problem: "How can supply chains be made more transparent?", solution: "AI generates code for supply chain visibility tools, enabling real-time monitoring and data-driven decisions.", aiTool: "GitHub Copilot", icon: "../assets/GitHubCopilot.jpg" },
  { id: 97, domain: "Logistics", title: "Delivery Optimization", problem: "How can delivery drivers optimize their routes?", solution: "AI analyzes traffic patterns, customer locations, and delivery history to suggest optimal delivery routes.", aiTool: "Google Maps AI", icon: "../assets/GoogleMapsAI.jpg" },
  { id: 98, domain: "Logistics", title: "Fleet Management", problem: "How can companies manage their fleets efficiently?", solution: "AI analyzes vehicle data, driver behavior, and maintenance logs to optimize fleet operations.", aiTool: "Amazon SageMaker", icon: "../assets/AmazonSageMaker.jpg" },
  { id: 99, domain: "Logistics", title: "AI-Driven Warehouse Robotics", problem: "How can warehouses automate order picking and packing?", solution: "AI controls robots to optimize picking routes and packing efficiency.", aiTool: "Locus Robotics AI", icon: "../assets/LocusRoboticsAI.jpg" },

  // Smart Home
  { id: 160, domain: "Smart Home", title: "Home Automation", problem: "How can smart homes be made more autonomous?", solution: "AI generates code for home automation infrastructure, enabling real-time monitoring and data-driven decisions.", aiTool: "GitHub Copilot", icon: "githubmark.png" },
  { id: 161, domain: "Smart Home", title: "Smart Lighting", problem: "How can smart homes optimize their lighting?", solution: "AI analyzes home data, identifies inefficiencies, and provides actionable recommendations.", aiTool: "Amazon SageMaker", icon: "AmazonSageMaker.jpg" },
  { id: 162, domain: "Smart Home", title: "AI-Powered Home Security Drones", problem: "How can smart homes monitor their surroundings autonomously?", solution: "AI controls indoor/outdoor drones to patrol and alert homeowners of unusual activity.", aiTool: "Sunflower Labs AI", icon: "SunflowerLabsAI.jpg" }
];

export default useCases;