const toolUrls = {
  "OpenAI GPT-4": "https://platform.openai.com/",
  "GPT-4": "https://platform.openai.com/",
  "Rev AI": "https://www.rev.ai/",
  "Copyscape AI": "https://www.copyscape.com/",
  "Taboola AI": "https://www.taboola.com/ai/",
  "Perspective API": "https://perspectiveapi.com/",
  "Google Vision AI": "https://cloud.google.com/vision/",
  "YOLOv5": "https://github.com/ultralytics/yolov5",
  "Microsoft Face API": "https://azure.microsoft.com/en-us/services/cognitive-services/face/",
  "Tesseract OCR": "https://github.com/tesseract-ocr/tesseract",
  "Aidoc AI": "https://www.aidoc.com/",
  "DALL-E": "https://labs.openai.com/",
  "GitHub Copilot": "https://github.com/features/copilot",
  "OpenAI Codex": "https://platform.openai.com/docs/guides/codex",
  "Selenium AI": "https://www.selenium.dev/",
  "Doxygen AI": "https://www.doxygen.nl/",
  "SonarQube AI": "https://www.sonarsource.com/",
  "DeepCode AI": "https://www.deepcode.ai/",
  "IBM Watson NLU": "https://www.ibm.com/watson/services/natural-language-understanding/",
  "Jasper AI": "https://www.jasper.ai/",
  "Amazon Personalize": "https://aws.amazon.com/personalize/",
  "Gradescope AI": "https://www.gradescope.com/",
  "Google Flights AI": "https://www.google.com/flights",
  "Google Maps AI": "https://cloud.google.com/maps-platform/",
  "Amazon Translate": "https://aws.amazon.com/translate/",
  "Google Places AI": "https://developers.google.com/maps/documentation/places/web-service/overview",
  "Google Sheets AI": "https://workspace.google.com/marketplace/app/sheetai/",
  "Google Cloud AI": "https://cloud.google.com/ai-platform/",
  "Google AI": "https://ai.google/",
  "AWS AI": "https://aws.amazon.com/machine-learning/",
  "Amazon SageMaker": "https://aws.amazon.com/sagemaker/",
  "AWS Fraud Detector": "https://aws.amazon.com/fraud-detector/",
  "Vue.ai": "https://vue.ai/",
  "AWS Rekognition": "https://aws.amazon.com/rekognition/",
  "AutoGrid Flex AI": "https://www.auto-grid.com/",
  "Llamasoft AI": "https://www.llamasoft.com/ai/",
  "DJI Terra AI": "https://www.dji.com/terra",
  "Matterport AI": "https://matterport.com/",
  "Locus Robotics AI": "https://locusrobotics.com/",
  "Relativity AI": "https://www.relativity.com/",
  "Deep Genomics": "https://www.deepgenomics.com/",
  "Philips HealthSuite AI": "https://www.philips.com/a-w/about/healthsuite.html",
  "DeepMind AlphaFold": "https://www.deepmind.com/research/highlighted-research/alphafold",
  "Google Dialogflow": "https://dialogflow.cloud.google.com/",
  "Google Health AI": "https://health.google/health-ai/",
  "Google Cloud Price AI": "https://cloud.google.com/solutions/price-optimization",
  "Cogito AI": "https://www.cogitocorp.com/", 
  "Amazon Alexa": "https://developer.amazon.com/en-US/alexa", 
  "Google Knowledge Graph": "https://developers.google.com/knowledge-graph", 
  "Google Translate AI": "https://translate.google.com/", 
  "Guru AI": "https://www.getguru.com/", 
  "AWS Transcribe": "https://aws.amazon.com/transcribe/", 
  "Amazon Polly": "https://aws.amazon.com/polly/", 
  "Apple VoiceOver": "https://www.apple.com/accessibility/vision/", 
  "OpenCV AI": "https://opencv.org/", 
  "Magnifier AI": "https://www.microsoft.com/en-us/p/magnifier/9wzdncrfj9bn", 
  "SignAll AI": "https://www.signall.us/", 
  "Splunk AI": "https://www.splunk.com/en_us/solutions/ai-ml.html", 
  "FICO Score AI": "https://www.fico.com/en/products/fico-score", 
  "Quantitative AI": "https://quantitative.ai/", 
  "ComplyAdvantage AI": "https://complyadvantage.com/", 
  "Syte Visual AI": "https://www.syte.ai/", 
  "Sunflower Labs AI": "https://www.sunflower-labs.com/"
};

export default toolUrls; 